[project]
drom-version = "0.1"
share-repo = "https://github.com/OCamlPro/drom-share"
share-version = "0.9.1"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@ocamlpro.com>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "OCamlPro SAS"
edition = "4.13.0"
github-organization = "ocamlpro"
license = "GPL3"
min-edition = "4.10.0"
name = "autofonce"
skeleton = "program"
synopsis = "A modern runner for GNU Autoconf Testsuites"
version = "1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
autofonce is a modern runner for GNU Autoconf Testsuites:
autofonce has a limited understanding of m4 macros that appear in testsuites
written for the GNU Autoconf testsuites, and can run such tests in a modern
way.
"""

[project]
skip = ["@test", "tests", "CHANGES.md", ".github/workflows/workflow.yml", "sphinx/install.rst", "sphinx/index.rst", "sphinx/about.rst"]

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
# examples:
#  docker-alpine-image = "ocamlpro/ocaml:4.13"
#  dune-lang = "2.1"
#  readme-trailer = "..."
#  dot-gitignore-trailer = "..."
[fields]
docker-alpine-image = "ocamlpro/ocaml:4.12"
dot-gitignore-trailer = """
/autofonce-*.bin
/gh-pages
*.exe
"""
readme-trailer = """

## Main Features

* automatic run from any directory in the project
* short display focusing on failed tests
* automatic parallel execution
* promotion of tests results to fix tests

## Example of Autofonce Test

Here is a simple example of test understood by `autofonce`:

```
# Start of a test, and the name that will be displayed
AT_SETUP([Example test])

# can be used to select tests to run:
AT_KEYWORDS([example test autofonce]) 

# create a file `file` with its content
AT_DATA([file], [
content of file
on multiple lines
])

# call some command, check its exit code, stdout, stderr
AT_CHECK([cat file], [0], [stdout of my command], [stderr of my command])
# you can do more, ignore some results, run more tests in case of failure, etc.

# end of the test
AT_CLEANUP
```

Now, copy this test in a file `test.at`, and run `autofonce`:
```
$ autofonce init
$ autofonce run -T test.at
Project description loaded from $PWD/autofonce.toml
Loading tests from file "$PWD/test.at"
Creating testing directory $PWD/_autofonce

0001 Example test                    FAIL (test.at:14:0 stdout stderr)
Results:
* 1 checks performed
* 0 / 1 tests executed successfully
* 1 tests failed: 0001
File "$PWD/_autofonce/results.log" created with failure results
zsh: exit 1     autofonce run -T test.at
```

"""
static-clibs = "ANSITerminal_stubs"

[[package]]
dir = "src/autofonce"
# edit 'src/autofonce/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_core"
# edit 'src/autofonce_core/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_lib"
# edit 'src/autofonce_lib/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_m4"
# edit 'src/autofonce_m4/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_share"
# edit 'src/autofonce_share/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_patch"
# edit 'src/autofonce_patch/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_config"
# edit 'src/autofonce_config/package.toml' for package-specific options

[[package]]
dir = "src/autofonce_misc"
# edit 'src/autofonce_misc/package.toml' for package-specific options

[[package]]
dir = "src/ez_win32"

[[package]]
dir = "src/ez_call"

